theme: jekyll-theme-minimal
title: Ashley Kang
description: I'm a Computer Sciecne student at the University of Alberta with a focus on software development and game design. I've always been passionate about games and look forward to joining a team that's just as passionate as I am!
